new validators
SwapnilSoni1999/express-dry pull request #7
Opened 2021-09-30 21:52 UTC by kehshiba

2021-09-30 21:59 UTC, SwapnilSoni1999 commented on validators/Aadhar_IN.js
> +    if (typeof x !== 'string') {
1. Aadhar card number can be in string or number
2. Aadhar length needs to be checked
3. `x` should be overwritten with to use `.length` and `.match` in future execution

2021-09-30 22:00 UTC, SwapnilSoni1999 commented on validators/DRIVING_LC_IN.js
> +        return { success: false, message: 'Invalid Driving License' }
- typeof check should return the data type we're expecting

2021-09-30 22:05 UTC, SwapnilSoni1999 commented on validators/PAN_IN.js
> +        return { success: false, message: 'Invalid PAN Number' }
- again, type check should return the data type we're expecting

2021-09-30 22:05 UTC, SwapnilSoni1999 requested changes
Please do the following changes!

2021-09-30 22:06 UTC, SwapnilSoni1999 commented
Also please rebase your commits in proper messages for seperate files

2021-09-30 22:31 UTC, kehshiba commented
hey i did some changes?

2021-09-30 22:38 UTC, kehshiba commented
do i have to change the message text? also i'm learning about how to rebase now but i commited though?

2021-09-30 23:53 UTC, SwapnilSoni1999 commented
> do i have to change the message text? also i'm learning about how to rebase now but i commited though?

You can learn more about how to rebase your commits from github docs

2021-10-01 10:27 UTC, SwapnilSoni1999 commented
Since the issue is resolved by #8 #9

2021-10-01 10:27 UTC, closed without merging